Test /deploy-app

diff --git a/.github/workflows/app-ci-cd-gcp.yml b/.github/workflows/app-ci-cd-gcp.yml
--- a/.github/workflows/app-ci-cd-gcp.yml
+++ b/.github/workflows/app-ci-cd-gcp.yml
@@ -3,7 +3,7 @@ name: Continuous Integration and Continuous Deployment
 run-name: ${{ github.actor }} submitted a CI CD Action
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "milestone5" ]
 
 jobs:
   Explore-GitHub-Actions:
@@ -22,6 +22,17 @@ jobs:
           credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
       - name: Configure Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v1
+      # - name: Debug Docker Configuration
+      #   run: |
+      #     echo "Checking Docker version"
+      #     docker --version || echo "Docker not installed"
+      #     echo "Checking Docker config directory"
+      #     ls -la ~/.docker || echo "No Docker directory"
+      #     echo "Checking Docker config file"
+      #     cat ~/.docker/config.json || echo "Docker config not found"
+      - name: Configure Docker Client
+        run: |-
+          gcloud auth configure-docker # --quiet #authenticate to gcr
       - name: Configure Docker Client
         run: |-
           gcloud auth configure-docker # --quiet #authenticate to gcr
@@ -36,13 +47,13 @@ jobs:
           docker build -t preppal-app-deployment -f Dockerfile .
       - name: Run Deploy App
         run: |-
+          echo "Deploy APP"
+          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
           docker run --rm --name preppal-app-deployment \
             -v /var/run/docker.sock:/var/run/docker.sock \
             -v $HOME/.ssh:/home/app/.ssh \
             -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
-            -v ${{ github.workspace }}/src/api-service:/api-service \
-            -v ${{ github.workspace }}/src/data-collector:/data-collector \
-            -v ${{ github.workspace }}/src/data-processor:/data-processor \
+            -v ${{ github.workspace }}/src/apiservice:/api-service \
             --volume $GITHUB_WORKSPACE:/workspace \
             --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
             --env GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
